# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: src/Application/**
  pull_request:
    branches: [ "main" ]
    paths: src/Application/**

env:
  registryName: 4qherpa7hb2fimpnpreg.azurecr.io
  repositoryName: techexcel/dotnetcoreapp
  dockerFolderPath: ./src/Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  buildAndPushImage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Docker login
      uses: docker/login-action@v1.9.0
      with:
        registry: ${{secrets.ACR_LOGIN_SERVER}}
        username: ${{secrets.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}
        logout: true
    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  deployToDev:
    runs-on: ubuntu-latest
    needs: buildAndPushImage
    environment:
      name: dev
      url: https://4qherpa7hb2fi-dev.azurewebsites.net/
    steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 4qherpa7hb2fi-dev
        images: 4qherpa7hb2fimpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deployToTest:
    runs-on: ubuntu-latest
    needs: deployToDev
    environment:
      name: test
      url: https://4qherpa7hb2fi-test.azurewebsites.net/
    steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 4qherpa7hb2fi-test
        images: 4qherpa7hb2fimpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deployToProd:
    runs-on: ubuntu-latest
    needs: deployToTest
    environment:
      name: prod
      url: https://4qherpa7hb2fi-prod.azurewebsites.net/
    steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 4qherpa7hb2fi-prod
        images: 4qherpa7hb2fimpnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}